version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install .[remote] --group docs
    pre_build:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" != "tag" ];
        then
          towncrier build --version Unreleased --yes;
        fi
    build:
        html:
          - mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
mkdocs:
  configuration: mkdocs.yml
